let tripData = [
  {
    "id": 1,
    "userID": 44,
    "destinationID": 49,
    "travelers": 1,
    "date": "2022/09/16",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  },
  {
    "id": 2,
    "userID": 35,
    "destinationID": 25,
    "travelers": 5,
    "date": "2022/10/04",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 3,
    "userID": 3,
    "destinationID": 22,
    "travelers": 4,
    "date": "2022/05/22",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 4,
    "userID": 43,
    "destinationID": 14,
    "travelers": 2,
    "date": "2022/02/25",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 5,
    "userID": 42,
    "destinationID": 29,
    "travelers": 3,
    "date": "2022/04/30",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 6,
    "userID": 29,
    "destinationID": 35,
    "travelers": 3,
    "date": "2022/06/29",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 7,
    "userID": 37,
    "destinationID": 17,
    "travelers": 5,
    "date": "2022/5/28",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 8,
    "userID": 36,
    "destinationID": 39,
    "travelers": 6,
    "date": "2022/02/07",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 9,
    "userID": 24,
    "destinationID": 19,
    "travelers": 5,
    "date": "2022/12/19",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 10,
    "userID": 9,
    "destinationID": 50,
    "travelers": 6,
    "date": "2022/07/23",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 11,
    "userID": 50,
    "destinationID": 5,
    "travelers": 4,
    "date": "2022/10/14",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 12,
    "userID": 33,
    "destinationID": 33,
    "travelers": 6,
    "date": "2022/10/17",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 13,
    "userID": 14,
    "destinationID": 12,
    "travelers": 1,
    "date": "2022/02/12",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 14,
    "userID": 19,
    "destinationID": 35,
    "travelers": 1,
    "date": "2022/09/24",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 15,
    "userID": 50,
    "destinationID": 13,
    "travelers": 3,
    "date": "2022/07/04",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 16,
    "userID": 19,
    "destinationID": 27,
    "travelers": 1,
    "date": "2022/11/20",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 17,
    "userID": 28,
    "destinationID": 31,
    "travelers": 1,
    "date": "2022/10/30",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 18,
    "userID": 18,
    "destinationID": 2,
    "travelers": 2,
    "date": "2022/09/25",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 19,
    "userID": 47,
    "destinationID": 47,
    "travelers": 4,
    "date": "2022/07/21",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 20,
    "userID": 41,
    "destinationID": 19,
    "travelers": 4,
    "date": "2022/10/05",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 21,
    "userID": 12,
    "destinationID": 10,
    "travelers": 1,
    "date": "2022/01/28",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 22,
    "userID": 22,
    "destinationID": 9,
    "travelers": 4,
    "date": "2022/05/01",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 23,
    "userID": 14,
    "destinationID": 24,
    "travelers": 6,
    "date": "2022/01/02",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 24,
    "userID": 46,
    "destinationID": 26,
    "travelers": 5,
    "date": "2019/11/15",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 25,
    "userID": 18,
    "destinationID": 12,
    "travelers": 6,
    "date": "2019/10/26",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 26,
    "userID": 25,
    "destinationID": 15,
    "travelers": 3,
    "date": "2019/12/10",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 27,
    "userID": 43,
    "destinationID": 7,
    "travelers": 6,
    "date": "2019/07/16",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 28,
    "userID": 48,
    "destinationID": 31,
    "travelers": 3,
    "date": "2020/02/03",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 29,
    "userID": 42,
    "destinationID": 25,
    "travelers": 3,
    "date": "2019/08/30",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 30,
    "userID": 33,
    "destinationID": 29,
    "travelers": 1,
    "date": "2020/07/17",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 31,
    "userID": 11,
    "destinationID": 33,
    "travelers": 3,
    "date": "2020/12/19",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 32,
    "userID": 34,
    "destinationID": 36,
    "travelers": 5,
    "date": "2020/05/06",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 33,
    "userID": 6,
    "destinationID": 36,
    "travelers": 5,
    "date": "2020/03/26",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 34,
    "userID": 32,
    "destinationID": 14,
    "travelers": 5,
    "date": "2019/08/02",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 35,
    "userID": 36,
    "destinationID": 1,
    "travelers": 3,
    "date": "2020/10/23",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 36,
    "userID": 30,
    "destinationID": 26,
    "travelers": 5,
    "date": "2019/10/20",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 37,
    "userID": 49,
    "destinationID": 24,
    "travelers": 2,
    "date": "2021/02/20",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 38,
    "userID": 47,
    "destinationID": 20,
    "travelers": 2,
    "date": "2020/11/16",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 39,
    "userID": 42,
    "destinationID": 25,
    "travelers": 3,
    "date": "2019/10/22",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 40,
    "userID": 29,
    "destinationID": 50,
    "travelers": 3,
    "date": "2020/10/31",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 41,
    "userID": 3,
    "destinationID": 25,
    "travelers": 3,
    "date": "2020/08/30",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 42,
    "userID": 11,
    "destinationID": 32,
    "travelers": 1,
    "date": "2020/08/08",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 43,
    "userID": 50,
    "destinationID": 42,
    "travelers": 4,
    "date": "2021/01/09",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 44,
    "userID": 27,
    "destinationID": 43,
    "travelers": 3,
    "date": "2020/09/12",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 45,
    "userID": 45,
    "destinationID": 5,
    "travelers": 6,
    "date": "2020/09/06",
    "duration": 9,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 46,
    "userID": 44,
    "destinationID": 33,
    "travelers": 2,
    "date": "2020/08/24",
    "duration": 11,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 47,
    "userID": 28,
    "destinationID": 32,
    "travelers": 3,
    "date": "2019/12/10",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 48,
    "userID": 44,
    "destinationID": 14,
    "travelers": 6,
    "date": "2021/02/10",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 49,
    "userID": 45,
    "destinationID": 35,
    "travelers": 1,
    "date": "2020/05/14",
    "duration": 16,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 50,
    "userID": 3,
    "destinationID": 16,
    "travelers": 5,
    "date": "2020/07/02",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 51,
    "userID": 16,
    "destinationID": 27,
    "travelers": 2,
    "date": "2020/01/16",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 52,
    "userID": 46,
    "destinationID": 14,
    "travelers": 2,
    "date": "2020/01/24",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 53,
    "userID": 27,
    "destinationID": 4,
    "travelers": 6,
    "date": "2020/01/03",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 54,
    "userID": 48,
    "destinationID": 21,
    "travelers": 2,
    "date": "2020/09/27",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 55,
    "userID": 39,
    "destinationID": 49,
    "travelers": 3,
    "date": "2020/03/08",
    "duration": 6,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 56,
    "userID": 23,
    "destinationID": 21,
    "travelers": 3,
    "date": "2020/06/14",
    "duration": 19,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 57,
    "userID": 33,
    "destinationID": 17,
    "travelers": 2,
    "date": "2019/07/04",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 58,
    "userID": 40,
    "destinationID": 36,
    "travelers": 4,
    "date": "2020/10/27",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 59,
    "userID": 21,
    "destinationID": 44,
    "travelers": 4,
    "date": "2020/01/27",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 60,
    "userID": 17,
    "destinationID": 45,
    "travelers": 2,
    "date": "2020/06/23",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 61,
    "userID": 26,
    "destinationID": 19,
    "travelers": 2,
    "date": "2020/07/25",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 62,
    "userID": 19,
    "destinationID": 37,
    "travelers": 4,
    "date": "2020/08/07",
    "duration": 8,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 63,
    "userID": 26,
    "destinationID": 35,
    "travelers": 5,
    "date": "2020/11/03",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 64,
    "userID": 45,
    "destinationID": 25,
    "travelers": 3,
    "date": "2020/08/26",
    "duration": 7,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 65,
    "userID": 3,
    "destinationID": 35,
    "travelers": 4,
    "date": "2020/03/21",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 66,
    "userID": 17,
    "destinationID": 31,
    "travelers": 6,
    "date": "2020/12/19",
    "duration": 10,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 67,
    "userID": 36,
    "destinationID": 47,
    "travelers": 5,
    "date": "2020/04/25",
    "duration": 15,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 68,
    "userID": 44,
    "destinationID": 41,
    "travelers": 6,
    "date": "2020/09/19",
    "duration": 14,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 69,
    "userID": 40,
    "destinationID": 7,
    "travelers": 6,
    "date": "2019/11/16",
    "duration": 12,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 70,
    "userID": 21,
    "destinationID": 17,
    "travelers": 3,
    "date": "2019/10/01",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 71,
    "userID": 38,
    "destinationID": 28,
    "travelers": 1,
    "date": "2020/05/26",
    "duration": 11,
    "status": "pending",
    "suggestedActivities": []
  }, {
    "id": 72,
    "userID": 38,
    "destinationID": 25,
    "travelers": 2,
    "date": "2019/12/30",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 73,
    "userID": 17,
    "destinationID": 14,
    "travelers": 2,
    "date": "2020/04/26",
    "duration": 18,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 74,
    "userID": 9,
    "destinationID": 31,
    "travelers": 5,
    "date": "2020/03/05",
    "duration": 13,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 75,
    "userID": 34,
    "destinationID": 28,
    "travelers": 2,
    "date": "2020/12/30",
    "duration": 4,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 76,
    "userID": 7,
    "destinationID": 17,
    "travelers": 5,
    "date": "2019/10/22",
    "duration": 20,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 77,
    "userID": 7,
    "destinationID": 46,
    "travelers": 5,
    "date": "2020/05/28",
    "duration": 17,
    "status": "approved",
    "suggestedActivities": []
  }, {
    "id": 78,
    "userID": 37,
    "destinationID": 17,
    "travelers": 3,
    "date": "2020/11/07",
    "duration": 5,
    "status": "approved",
    "suggestedActivities": []
  }
];
export default tripData
